/**
 * D1.3 (plano `2026-10-01-incendio-backlog-pos-roadmap.md`) — AS ATIVIDADES DA IT 09 DO CBMMG.
 *
 * A Tabela A.1 (Anexo A, pp. 6–21) da IT 09 (Carga de Incêndio, 2ª ed., Portaria 61/2020): cada
 * ATIVIDADE com a divisão de ocupação e a carga de incêndio específica (MJ/m²). Quando a tabela
 * não dá número (remete aos Anexos B/C ou à atividade específica), a carga é `null` e a nota diz.
 *
 * GERADO de `docs/normas/incendio-mg/it09-tabela-a1.tsv` (a transcrição; o teste
 * `incendioAtividadesMG.test.ts` confere este arquivo contra ela). Não editar à mão.
 */

/** [descrição, divisão, carga MJ/m² (ou `null`), nota quando a carga é `null`]. */
export type AtividadeIT09 = readonly [descricao: string, divisao: string, cargaMJm2: number | null, nota?: string];

export const ATIVIDADES_IT09: readonly AtividadeIT09[] = [
  ["Alojamentos", 'A-3', 300],
  ["Casas térreas ou assobradadas (isoladas e não isoladas)", 'A-1', 300],
  ["Condomínios horizontais", 'A-1', 300],
  ["Conventos", 'A-3', 300],
  ["Edifícios de apartamentos", 'A-2', 300],
  ["Internatos", 'A-3', 300],
  ["Mosteiros", 'A-3', 300],
  ["Pensionatos", 'A-3', 300],
  ["Residências geriátricas (com capacidade máxima de 16 leitos), sem acompanhamento médico", 'A-3', 300],
  ["Residências terapêuticas", 'A-1', 300],
  ["Albergues", 'B-1', 500],
  ["Apart-hotéis", 'B-2', 500],
  ["Campings", 'B-1', 500],
  ["Flats", 'B-2', 500],
  ["Habitação coletiva com mais de 16 leitos", 'B-1', 500],
  ["Hospedarias", 'B-1', 500],
  ["Hotéis", 'B-1', 500],
  ["Hotéis e assemelhados com cozinha própria nos apartamentos", 'B-2', 500],
  ["Hotéis residenciais", 'B-2', 500],
  ["Motéis", 'B-1', 500],
  ["Pensões", 'B-1', 500],
  ["Pousadas", 'B-1', 500],
  ["Açúcar", 'C-2', 1000],
  ["Algodão", 'C-2', 600],
  ["Andaimes - aluguel", 'C-1', 300],
  ["Animais - atacado de animais vivos e ovos", 'C-1', 300],
  ["Animais - varejo de animais vivos, de artigos e alimentos para animais de estimação (\"pet shop\")", 'C-2', 600],
  ["Antiguidades", 'C-2', 700],
  ["Aparelhos eletrodomésticos e equipamentos de áudio e vídeo, incluindo peças e acessórios", 'C-1', 300],
  ["Aparelhos eletrônicos e componentes, equipamentos de telefonia, comunicação e informática", 'C-2', 400],
  ["Armarinhos - varejo", 'C-1', 300],
  ["Armas e munições", 'C-2', 800],
  ["Artesanatos e souvenirs", 'C-1', 300],
  ["Bebidas - água, cerveja, chope, refrigerante", 'C-1', 80],
  ["Bebidas - vinho, saquê, cidra", 'C-1', 200],
  ["Bebidas destiladas", 'C-2', 500],
  ["Bijuteria, artigos de metal e vidro", 'C-1', 300],
  ["Bolsas, malas e artigos de viagem", 'C-2', 600],
  ["Bombas e compressores; partes e peças", 'C-1', 200],
  ["Borracha, cortiça, couro, feltro, espuma - artigos", 'C-2', 600],
  ["Brinquedos e artigos recreativos", 'C-2', 500],
  ["Caça, pesca e camping - artigos", 'C-2', 800],
  ["Cacau", 'C-2', 400],
  ["Café", 'C-2', 400],
  ["Caixões e urnas", 'C-2', 500],
  ["Cal, areia, pedra britada, tijolos e telhas", 'C-1', 300],
  ["Calçados", 'C-2', 600],
  ["Carnes - atacado ou varejo (açougue) de carnes e derivados, pescados e frutos do mar", 'C-1', 40],
  ["Carvão e lenha", 'C-2', 3000],
  ["Centros comerciais de compras (Shopping centers)", 'C-3', 800],
  ["Cera, artigos de", 'C-2', 2100],
  ["Cereais e leguminosas beneficiados, farinhas, amidos e féculas", 'C-2', 2000],
  ["Cimento", 'C-1', 40],
  ["Comércio atacadista de cigarros, cigarrilhas, charutos", 'C-2', 800],
  ["Cosméticos, produtos de perfumaria e higiene pessoal", 'C-2', 400],
  ["Couros, lãs, peles e outros subprodutos não-comestíveis de origem animal - atacado", 'C-2', 500],
  ["Defensivos agrícolas, adubos, fertilizantes e corretivos do solo (exceto cujos componentes possuem característica potencialmente explosiva ou combustível)", 'C-1', 200],
  ["Doces, chocolates, confeitos, balas, bombons e semelhantes", 'C-2', 400],
  ["Embalagens", 'C-2', 800],
  ["Esporte, artigos de", 'C-2', 800],
  ["Ferragens e ferramentas", 'C-1', 300],
  ["Filmes, CDs, DVDs, fitas e discos", 'C-2', 600],
  ["Floricultura - sementes, flores, plantas e gramas", 'C-1', 80],
  ["Fotografia - artigos fotográficos e para filmagem", 'C-1', 300],
  ["Galeria de quadros", 'C-1', 200],
  ["Hortifrutigranjeiros", 'C-1', 200],
  ["Iluminação - artigos", 'C-2', 500],
  ["Instrumentos e materiais para uso médico, cirúrgico, hospitalar e de laboratórios", 'C-1', 300],
  ["Instrumentos musicais e acessórios", 'C-2', 600],
  ["Joalheria", 'C-1', 300],
  ["Leite, laticínios e frios", 'C-1', 200],
  ["Livros, jornais, revistas e outras publicações", 'C-2', 1000],
  ["Lojas de conveniência", 'C-2', 400],
  ["Lojas de departamentos ou magazines", 'C-2', 800],
  ["Lojas de variedades, exceto lojas de departamentos ou magazines", 'C-2', 600],
  ["Lubrificantes (comércio varejista)", 'C-2', 1000],
  ["Lustres, luminárias e abajures", 'C-1', 40],
  ["Madeira - estruturas para locação", 'C-2', 1000],
  ["Madeira e artefatos - varejo", 'C-2', 800],
  ["Madeira e artefatos com tratamento ou impregnação - varejo", 'C-2', 3000],
  ["Madeira e produtos derivados - atacado", 'C-2', 3000],
  ["Máquinas e equipamentos não especificados nesta tabela; partes e peças", 'C-1', 300],
  ["Máquinas e equipamentos para costura ou escritórios", 'C-1', 300],
  ["Máquinas e equipamentos para uso comercial; partes e peças", 'C-1', 300],
  ["Máquinas e equipamentos para uso industrial; partes e peças", 'C-1', 200],
  ["Máquinas, aparelhos e equipamentos para uso agropecuário; partes e peças", 'C-1', 300],
  ["Máquinas, aparelhos e equipamentos para uso odonto- médico-hospitalar; partes e peças", 'C-1', 200],
  ["Máquinas, equipamentos para terraplenagem, mineração e construção; partes e peças", 'C-1', 300],
  ["Massas alimentícias", 'C-2', 1000],
  ["Materiais de construção em geral", 'C-2', 800],
  ["Materiais elétricos e hidráulicos", 'C-1', 300],
  ["Materiais para festas", 'C-2', 1000],
  ["Matérias-primas agrícolas (exceto cujos componentes possuem característica potencialmente explosiva ou combustível)", 'C-2', 500],
  ["Móveis (exceto colchoaria)", 'C-2', 600],
  ["Móveis com colchoaria", 'C-2', 1000],
  ["Objetos de arte", 'C-1', 200],
  ["Odontológico, produtos", 'C-1', 300],
  ["Óleos e gorduras", 'C-2', 1000],
  ["Óptica", 'C-1', 300],
  ["Pães, bolos, biscoitos e similares", 'C-2', 1000],
  ["Palcos, coberturas e outras estruturas de uso temporário (exceto andaimes) - aluguel", 'C-2', 400],
  ["Papel de parede e similares", 'C-2', 500],
  ["Papel e papelão em geral - atacado", 'C-2', 800],
  ["Papelão betuminado", 'C-2', 2000],
  ["Papelaria e artigos de escritórios", 'C-2', 700],
  ["Pedras para acabamento e revestimento", 'C-1', 40],
  ["Pilhas, baterias e acumuladores elétricos", 'C-2', 800],
  ["Plástico - artigos", 'C-2', 1000],
  ["Pneus, pneumáticos e câmaras-de-ar", 'C-2', 700],
  ["Produtos adesivos", 'C-2', 1000],
  ["Produtos da extração mineral, exceto combustíveis", 'C-1', 200],
  ["Produtos de limpeza", 'C-2', 2000],
  ["Produtos e artigos de argila, barro e olaria", 'C-1', 200],
  ["Produtos farmacêuticos, medicamentos e drogas de uso humano e veterinário", 'C-2', 1000],
  ["Produtos para piscina, inseticidas, repelentes", 'C-2', 500],
  ["Produtos químicos e petroquímicos", 'C-2', 4000],
  ["Produtos siderúrgicos e metalúrgicos (exceto para construção)", 'C-1', 200],
  ["Próteses e artigos de ortopedia", 'C-1', 300],
  ["Rações/alimentos para animais - atacado de alimentos para animais", 'C-2', 2000],
  ["Relojoaria", 'C-2', 600],
  ["Resíduos e sucatas metálicos", 'C-1', 200],
  ["Resíduos e sucatas não metálicos", 'C-2', 800],
  ["Resinas e elastômeros", 'C-2', 3000],
  ["Sisal", 'C-2', 600],
  ["Soja", 'C-2', 1700],
  ["Solventes", 'C-2', 4000],
  ["Sorvetes", 'C-1', 80],
  ["Supermercado (mercados em geral)", 'C-2', 400],
  ["Tabacaria", 'C-1', 200],
  ["Tapeçaria, persianas e cortinas", 'C-2', 800],
  ["Têxteis e tecidos em geral", 'C-2', 700],
  ["Tintas (incluindo material de pintura), vernizes e similares", 'C-2', 1000],
  ["Toldos - aluguel", 'C-2', 800],
  ["Veículos automotores e embarcações (incluindo peças e acessórios)", 'C-1', 200],
  ["Veículos recreativos - bicicletas, triciclos, entre outros (incluindo peças e acessórios)", 'C-1', 200],
  ["Vidros, espelhos e vitrais", 'C-1', 300],
  ["Administração pública em geral", 'D-1', 700],
  ["Agências bancárias e similares", 'D-2', 300],
  ["Agências de correios, de serviços de postagem e similares", 'D-1', 400],
  ["Agências de notícias", 'D-1', 400],
  ["Agências de publicidade", 'D-1', 700],
  ["Agências de turismo", 'D-1', 700],
  ["Agências matrimoniais", 'D-1', 700],
  ["Alojamento, higiene e embelezamento de animais", 'D-1', 300],
  ["Aluguel de imóveis próprios", 'D-1', 700],
  ["Atividades auxiliares dos transportes aéreos, exceto operação dos aeroportos e campos de aterrissagem", 'D-1', 700],
  ["Atividades auxiliares dos transportes aquaviários", 'D-1', 700],
  ["Atividades de estética e outros serviços de cuidados com a beleza", 'D-1', 300],
  ["Atividades de gravação de som e de edição de música", 'D-1', 700],
  ["Atividades de limpeza não especificadas nesta tabela", 'D-1', 700],
  ["Atividades de produção cinematográfica, de vídeos e de programas de televisão, exceto auditórios", 'D-1', 300],
  ["Atividades de produção de fotografias", 'D-1', 300],
  ["Atividades de rádio", 'D-1', 300],
  ["Atividades de serviços de complementação diagnóstica e terapêutica não especificadas nesta tabela", 'D-4', 200],
  ["Atividades de transporte de valores", 'D-1', 700],
  ["Atividades de vigilância e segurança privada", 'D-1', 700],
  ["Cabeleireiros", 'D-1', 200],
  ["Captação, tratamento e distribuição de água e/ou esgoto", 'D-1', null, "Conforme atividade (ocupação) específica"],
  ["Cartórios", 'D-1', 700],
  ["Centrais telefônicas (telefonistas, telemarketing, callcenter, serviço de atendimento ao consumidor)", 'D-1', 200],
  ["Chaveiros", 'D-3', 200],
  ["Copiadora", 'D-1', 400],
  ["Distribuição de água por caminhões", 'D-1', 80],
  ["Encadernadoras", 'D-1', 400],
  ["Escafandria e Mergulho", 'D-1', 700],
  ["Escritórios e unidades de administração em geral", 'D-1', 700],
  ["Fornecimento de alimentos preparados (delivery), serviços de alimentação para eventos e recepções (buffet), cocção de alimentos, todos sem consumo no local de produção e sem caráter industrial", 'D-1', 300],
  ["Imunização e controle de pragas urbanas", 'D-1', 700],
  ["Instalação de máquinas e equipamentos industriais", 'D-3', 200],
  ["Instituições financeiras não incluídas em D-2", 'D-1', 700],
  ["Laboratórios clínicos", 'D-4', 200],
  ["Laboratórios de anatomia patológica e citológica", 'D-4', 200],
  ["Laboratórios fotográficos", 'D-4', 300],
  ["Laboratórios químicos", 'D-4', 500],
  ["Lavanderias", 'D-3', 300],
  ["Manutenção e reparação de aparelhos eletroeletrônicos fotográficos ópticos", 'D-3', 300],
  ["Manutenção e reparação de instrumentos musicais", 'D-3', 600],
  ["Manutenção e reparação elétricas em geral", 'D-3', 600],
  ["Manutenção e reparação hidráulicas ou mecânicas em geral, exceto automotivas", 'D-3', 200],
  ["Organismos internacionais e outras instituições extraterritoriais", 'D-1', 700],
  ["Organização logística do transporte de carga", 'D-1', 700],
  ["Outras atividades profissionais, científicas e técnicas não especificadas nesta tabela", 'D-1', 700],
  ["Pesquisa científica e desenvolvimento experimental", 'D-4', 300],
  ["Reparação de artigos do mobiliário", 'D-3', 500],
  ["Reparação de artigos têxteis em geral (roupas, calçados, bolsas e similares)", 'D-3', 700],
  ["Reparação de joias", 'D-3', 200],
  ["Reparação de relógios", 'D-3', 300],
  ["Reparação e manutenção de artigos borracha, cortiça, couro, feltro, espuma", 'D-3', 700],
  ["Reparação e manutenção de computadores e de equipamentos periféricos", 'D-3', 600],
  ["Repartições públicas", 'D-1', 700],
  ["Restauração de obras-de-arte", 'D-1', 300],
  ["Salas de acesso à internet", 'D-1', 400],
  ["Serviços advocatícios", 'D-1', 700],
  ["Serviços de adestramento de cães de guarda", 'D-1', 700],
  ["Serviços de arquitetura, engenharia e similares", 'D-1', 700],
  ["Serviços de bancos de células e tecidos humanos", 'D-4', 200],
  ["Serviços de cartografia, topografia e geodésia", 'D-1', 700],
  ["Serviços de computação em geral", 'D-1', 400],
  ["Serviços de cremação sem previsão de reunião de pessoas", 'D-1', 400],
  ["Serviços de diagnóstico por imagem, métodos ópticos ou registro gráfico", 'D-4', 200],
  ["Serviços de funerárias (exceto aqueles especificados no grupo F)", 'D-1', 400],
  ["Serviços de gravação de carimbos, exceto confecção", 'D-1', 700],
  ["Serviços de montagem de móveis de qualquer material", 'D-3', 200],
  ["Serviços de pintura", 'D-3', 500],
  ["Serviços de tatuagem e colocação de piercing", 'D-1', 300],
  ["Serviços de tradução, interpretação e similares", 'D-1', 700],
  ["Testes e análises técnicas", 'D-4', 300],
  ["Tinturarias", 'D-3', 300],
  ["Academias e espaços para atividades físicas em geral", 'E-3', 300],
  ["Atividades de fisioterapia", 'E-3', 200],
  ["Cursos de pilotagem", 'E-2', 300],
  ["Cursos preparatórios para concursos", 'E-1', 300],
  ["Educação infantil – creche, pré-escola e similares", 'E-5', 400],
  ["Educação profissional de nível técnico e tecnológico", 'E-4', 300],
  ["Educação superior – graduação, pós-graduação, extensão e similares", 'E-1', 300],
  ["Ensino de arte e cultura não especificado nesta tabela", 'E-2', 300],
  ["Ensino de artes cênicas, exceto dança", 'E-2', 300],
  ["Ensino de dança", 'E-3', 300],
  ["Ensino de esportes", 'E-3', 300],
  ["Ensino de idiomas", 'E-2', 300],
  ["Ensino de música", 'E-2', 300],
  ["Ensino fundamental", 'E-1', 300],
  ["Ensino médio", 'E-1', 300],
  ["Escola para portadores de deficiências", 'E-6', 300],
  ["Formação de condutores", 'E-4', 300],
  ["Sauna", 'E-3', 300],
  ["Treinamento em desenvolvimento profissional e gerencial", 'E-4', 300],
  ["Arquivos", 'F-1', 2000],
  ["Bibliotecas", 'F-1', 2000],
  ["Bibliotecas de acervo exclusivamente digital", 'F-1', 450],
  ["Casas de bingo, casas de apostas e similares", 'F-11', 600],
  ["Casas de show, casas noturnas, boates, restaurantes dançantes e assemelhados", 'F-6', 600],
  ["Cemitérios, crematórios, necrotérios, salas de funerais e assemelhados", 'F-2', 200],
  ["Centros de documentos históricos", 'F-1', 2000],
  ["Centros esportivos e de exibição (com arquibancada)", 'F-3', 150],
  ["Cinemas, teatros, auditórios e similares", 'F-5', 600],
  ["Circos e assemelhados", 'F-7', 500],
  ["Clubes sociais, esportivos e assemelhados", 'F-11', 300],
  ["Construções provisórias", 'F-7', 500],
  ["Estações e terminais de passageiros", 'F-4', 200],
  ["Eventos temporários, shows e assemelhados", 'F-7', 500],
  ["Exposições de objetos e de animais", 'F-10', null, "Anexo B ou C"],
  ["Feiras e similares", 'F-7', 500],
  ["Igrejas, templos, capelas, sinagogas, mesquitas e espaços assemelhados para reunião ou celebração religiosa", 'F-2', 200],
  ["Jogos recreativos eletrônicos, de cartas, de tabuleiro e similares", 'F-11', 600],
  ["Lanchonetes, cantinas, casas de chá, de sucos e similares", 'F-8', 300],
  ["Museus", 'F-1', 300],
  ["Padarias destinadas ao consumo in loco, sem fabricação própria", 'F-8', 300],
  ["Parques recreativos permanentes e assemelhados", 'F-9', 500],
  ["Restaurantes e bares", 'F-8', 300],
  ["Salões de festa, buffet e similares (todos com palco)", 'F-6', 600],
  ["Salões de festa, buffet e similares (todos sem palco)", 'F-11', 600],
  ["Sinuca, bilhar, boliches e similares", 'F-11', 600],
  ["Tiro ao alvo, estandes de tiro e similares", 'F-11', 600],
  ["Zoológicos, jardins botânicos, reservas ecológicas, áreas de proteção ambiental e assemelhados", 'F-9', 500],
  ["Abrigo para aeronaves com ou sem abastecimento", 'G-5', 300],
  ["Estacionamentos automáticos e estacionamentos com manobristas", 'G-1', 200],
  ["Estacionamentos de veículos com acesso de público", 'G-2', 200],
  ["Estacionamentos de veículos sem acesso de público", 'G-1', 200],
  ["Estacionamentos de veículos sem automação", 'G-2', 200],
  ["Local dotado de abastecimento de combustível", 'G-3', 300],
  ["Manutenção e reparação de aeronaves", 'G-5', 300],
  ["Oficinas de alinhamento e balanceamento de veículos automotores", 'G-4', 200],
  ["Oficinas de lanternagem ou funilaria e pintura de veículos automotores", 'G-4', 500],
  ["Oficinas de manutenção de máquinas agrícolas", 'G-4', 300],
  ["Oficinas de manutenção e reparação elétrica de veículos automotores", 'G-4', 600],
  ["Oficinas e serviços de manutenção, conservação e reparação de veículos", 'G-4', 300],
  ["Postos de abastecimento e serviço", 'G-3', 300],
  ["Serviços de borracharia para veículos automotores (sem recauchutagem)", 'G-4', 300],
  ["Asilos, abrigos geriátricos e similares", 'H-2', 350],
  ["Atividades de acupuntura", 'H-6', 200],
  ["Atividades de apoio à gestão de saúde", 'H-6', 200],
  ["Atividades de banco de leite humano", 'H-6', 200],
  ["Atividades de enfermagem sem internação", 'H-6', 200],
  ["Atividades de fonoaudiologia", 'H-6', 200],
  ["Atividades de podologia", 'H-6', 200],
  ["Atividades de profissionais da nutrição", 'H-6', 200],
  ["Atividades de psicologia e psicanálise", 'H-6', 200],
  ["Atividades de reprodução humana assistida", 'H-6', 200],
  ["Atividades de terapia ocupacional", 'H-6', 200],
  ["Atividade odontológica", 'H-6', 200],
  ["Casas de saúde, clínicas, unidades de urgência, ambulatórios e similares (todos com internação)", 'H-3', 300],
  ["Clínicas médicas e consultórios em geral (todos sem internação)", 'H-6', 200],
  ["Hospitais em geral", 'H-3', 300],
  ["Hospitais psiquiátricos", 'H-2', 350],
  ["Hospitais psiquiátricos, manicômios, reformatórios (todos com celas)", 'H-5', 100],
  ["Hospitais veterinários, clínicas e consultórios veterinários e similares", 'H-1', 300],
  ["Locais para tratamento de dependentes químicos e assemelhados", 'H-2', 350],
  ["Orfanatos e similares", 'H-2', 350],
  ["Outras atividades de atenção à saúde humana sem internação não especificadas nesta tabela", 'H-6', 200],
  ["Penitenciárias, casas de detenção, presídios e similares", 'H-5', 100],
  ["Postos policiais, Postos de bombeiros, Delegacias, entre outros", 'H-4', 700],
  ["Quartéis", 'H-4', 700],
  ["Reformatórios (sem celas)", 'H-2', 350],
  ["Serviços de vacinação e imunização humana", 'H-6', 200],
  ["Unidades de diálise e nefrologia", 'H-6', 200],
  ["Unidades de hemodiálise", 'H-6', 200],
  ["Unidades de hemoterapia", 'H-6', 200],
  ["Unidades de litotripsia", 'H-6', 200],
  ["Unidades de quimioterapia", 'H-6', 200],
  ["Unidades de radioterapia", 'H-6', 200],
  ["Abrasivos", 'I-1', 200],
  ["Absorventes higiênicos", 'I-2', 1000],
  ["Acabamentos gráficos, exceto encadernação e plastificação", 'I-2', 400],
  ["Aço (fundição)", 'I-1', 40],
  ["Aço em geral (arames, forjados, ao carbono, especiais, laminados, relaminados, trefilados, perfilados, produtos semi-acabados, tubos) exceto fundição", 'I-1', 200],
  ["Açúcar em geral (de cana refinado, de cereais, de beterraba, em bruto)", 'I-2', 800],
  ["Adesivos e selantes", 'I-2', 1000],
  ["Aditivos de uso industrial", 'I-2', 500],
  ["Adoçantes naturais e artificiais", 'I-2', 1000],
  ["Adubos, fertilizantes e similares (exceto cujos componentes possuem característica potencialmente explosiva ou combustível)", 'I-1', 200],
  ["Aeronaves", 'I-2', 600],
  ["Água", 'I-1', 80],
  ["Álcool", 'I-3', 4000],
  ["Alimentos dietéticos e complementos alimentares", 'I-2', 1000],
  ["Alimentos e pratos prontos", 'I-2', 800],
  ["Alimentos para animais e rações", 'I-3', 2000],
  ["Alumínio em geral (ligas em formas primárias, laminados)", 'I-1', 200],
  ["Alvejamento, tingimento e torção em fios, tecidos, artefatos têxteis e peças do vestuário", 'I-2', 700],
  ["Amidos e féculas de vegetais ( produtos, moagem, beneficiamento)", 'I-3', 2000],
  ["Aparelhamento de pedras para construção, exceto associado à extração", 'I-1', 40],
  ["Aparelhamento de placas e execução de trabalhos em mármore, granito, ardósia e outras pedras", 'I-1', 40],
  ["Aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo", 'I-1', 300],
  ["Aparelhos e equipamentos de medida, teste e controle", 'I-1', 300],
  ["Aparelhos e equipamentos para distribuição e controle de energia elétrica", 'I-1', 200],
  ["Aparelhos e utensílios para correção de defeitos físicos e aparelhos ortopédicos em geral", 'I-2', 500],
  ["Aparelhos elétricos de uso pessoal, peças e acessórios", 'I-1', 300],
  ["Aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação", 'I-1', 200],
  ["Aparelhos eletrodomésticos, outros não especificados nesta tabela, peças e acessórios", 'I-1', 300],
  ["Aparelhos fotográficos e cinematográficos, peças e acessórios", 'I-1', 300],
  ["Aparelhos telefônicos e de outros equipamentos de comunicação, peças e acessórios", 'I-1', 300],
  ["Aparelhos, equipamentos e acessórios de ar condicionado, refrigeração e ventilação", 'I-2', 1000],
  ["Arroz (produtos, moagem, beneficiamento)", 'I-3', 1700],
  ["Artefatos de joalheria e ourivesaria", 'I-1', 200],
  ["Artefatos de tanoaria e de embalagens de madeira", 'I-2', 800],
  ["Artefatos de tapeçaria", 'I-2', 700],
  ["Artefatos diversos de cortiça, bambu, palha, vime e outros materiais trançados, exceto móveis", 'I-2', 800],
  ["Artefatos diversos de madeira, exceto móveis", 'I-2', 800],
  ["Artefatos para pesca e esporte", 'I-2', 800],
  ["Artefatos têxteis para uso doméstico", 'I-2', 700],
  ["Artigos de carpintaria para construção", 'I-2', 800],
  ["Artigos de cutelaria", 'I-1', 200],
  ["Artigos de serralheria, exceto esquadrias", 'I-1', 200],
  ["Artigos ópticos", 'I-1', 300],
  ["Artigos para viagem, bolsas e semelhantes de qualquer material", 'I-2', 600],
  ["Automóveis, camionetas e utilitários", 'I-1', 300],
  ["Aviamentos para costura", 'I-2', 700],
  ["Azulejos pisos e semelhantes", 'I-1', 200],
  ["Bancos e estofados para veículos automotores", 'I-2', 600],
  ["Baterias e acumuladores para veículos automotores", 'I-2', 800],
  ["Bebidas - cervejas, chopes, refrigerantes, isotônicos, chá mate e outros chás prontos para consumo", 'I-1', 80],
  ["Bebidas - destilados e aguardentes em geral", 'I-2', 500],
  ["Bebidas - sucos de frutas, hortaliças e legumes", 'I-1', 200],
  ["Bebidas - vinho e outros fermentados não especificados nesta tabela", 'I-1', 200],
  ["Bebidas não-alcoólicas não especificadas nesta tabela", 'I-1', 80],
  ["Beneficiamento de café", 'I-2', 400],
  ["Bicicletas e triciclos não-motorizados, peças e acessórios", 'I-1', 200],
  ["Bijuterias e artefatos semelhantes", 'I-1', 200],
  ["Biocombustíveis", 'I-3', 4000],
  ["Biscoitos e bolachas", 'I-2', 400],
  ["Borracha (artefatos não especificados nesta tabela)", 'I-2', 600],
  ["Brinquedos e jogos recreativos não especificados nesta tabela", 'I-2', 500],
  ["Britamento de pedras", 'I-1', 40],
  ["Cabines, carrocerias e reboques para veículos automotores", 'I-1', 300],
  ["Cal e gesso", 'I-1', 80],
  ["Calçados e partes de calçados", 'I-2', 600],
  ["Caldeiras geradoras de vapor, exceto para aquecimento central e para veículos", 'I-1', 200],
  ["Caminhões e ônibus", 'I-1', 300],
  ["Canetas, lápis e outros artigos para escritório", 'I-2', 600],
  ["Cartolina e papel-cartão", 'I-2', 800],
  ["Casas de madeira pré-fabricadas", 'I-2', 800],
  ["Catalisadores", 'I-2', 500],
  ["Cera (produtos e artefatos em geral)", 'I-3', 2000],
  ["Cerâmicas e refratários (incluindo artefatos e produtos)", 'I-1', 200],
  ["Cerâmicos não-refratários não especificados nesta tabela", 'I-1', 200],
  ["Chapas e de embalagens de papelão ondulado", 'I-2', 800],
  ["Chapas, filmes, papéis e outros materiais e produtos químicos para fotografia", 'I-2', 500],
  ["Chassis com motor para automóveis, camionetas e utilitários", 'I-1', 300],
  ["Cigarros, fumo, cigarrilhas, charutos e semelhantes", 'I-1', 200],
  ["Cloro e álcalis", 'I-3', 2000],
  ["Colchões", 'I-3', 3000],
  ["Combustíveis nucleares", 'I-3', 4000],
  ["Componentes eletrônicos", 'I-1', 300],
  ["Compressores, peças e acessórios", 'I-1', 200],
  ["Concreto, argamassa, cimento, fibrocimento e materiais semelhantes (incluindo artefatos e produtos)", 'I-1', 40],
  ["Conservas de frutas, vegetais, legumes e semelhantes", 'I-1', 40],
  ["Conservas de peixes, crustáceos e moluscos", 'I-2', 500],
  ["Construção de embarcações", 'I-1', 300],
  ["Coquerias", 'I-3', 4000],
  ["Cordoaria (artefatos)", 'I-2', 700],
  ["Corte e dobra de metais", 'I-1', 200],
  ["Cosméticos, produtos de perfumaria e de higiene pessoal", 'I-1', 300],
  ["Couro (artefatos em geral, curtimento e outras preparações)", 'I-2', 600],
  ["Cronômetros e relógios", 'I-1', 300],
  ["Cunhagem de moedas e medalhas", 'I-1', 200],
  ["Decoração, lapidação, gravação, vitrificação e outros trabalhos em cerâmica, louça, vidro e cristal", 'I-1', 200],
  ["Defensivos agrícolas", 'I-1', 200],
  ["Desinfestantes domissanitários", 'I-2', 500],
  ["Edição de cadastros, listas e de outros produtos gráficos (com ou sem impressão)", 'I-2', 400],
  ["Edição de livros, jornais, revistas (com ou sem impressão)", 'I-2', 400],
  ["Elastômeros", 'I-3', 3000],
  ["Eletrodomésticos em geral, peças e acessórios", 'I-1', 300],
  ["Eletrodos, contatos e outros artigos de carvão e grafita para uso elétrico, eletroímãs e isoladores", 'I-1', 300],
  ["Equipamentos de informática", 'I-1', 300],
  ["Equipamentos de transmissão para fins industriais, exceto rolamentos", 'I-1', 200],
  ["Equipamentos de transporte não especificados nesta tabela", 'I-1', 300],
  ["Equipamentos e acessórios para segurança pessoal e profissional", 'I-2', 600],
  ["Equipamentos e aparelhos elétricos não especificados nesta tabela", 'I-1', 300],
  ["Equipamentos e instrumentos ópticos, peças e acessórios", 'I-1', 300],
  ["Equipamentos hidráulicos e pneumáticos, peças e acessórios, exceto válvulas", 'I-1', 200],
  ["Equipamentos para irrigação agrícola, peças e acessórios", 'I-1', 300],
  ["Equipamentos para sinalização e alarme", 'I-1', 300],
  ["Equipamentos transmissores de comunicação, peças e acessórios", 'I-1', 300],
  ["Escovas, pincéis e vassouras", 'I-2', 700],
  ["Especiarias, molhos, temperos e condimentos", 'I-1', 40],
  ["Esquadrias de madeira e de peças de madeira para instalações industriais e comerciais", 'I-2', 800],
  ["Estamparia e texturização em fios, tecidos, artefatos têxteis e peças do vestuário", 'I-2', 700],
  ["Estruturas metálicas", 'I-1', 200],
  ["Estufas e fornos elétricos para fins industriais, peças e acessórios", 'I-1', 200],
  ["Extração de gemas (pedras preciosas e semipreciosas)", 'I-1', 40],
  ["Extração de minerais não-metálicos (grafita, quartzo, amianto, etc.)", 'I-1', 40],
  ["Extração de minerais para fabricação de adubos, fertilizantes e outros produtos químicos (exceto cujos componentes possuem característica potencialmente explosiva ou combustível)", 'I-1', 200],
  ["Extração de petróleo e gás natural", 'I-3', 4000],
  ["Extração e beneficiamento de areias betuminosas", 'I-3', 3000],
  ["Extração e beneficiamento de carvão mineral", 'I-3', 3000],
  ["Extração e beneficiamento de xisto", 'I-3', 3000],
  ["Extração e britamento de pedras e outros materiais para construção e beneficiamento associado (ardósia, granito, mármore, calcário, dolomita, gesso, caulim, areia, cascalho, pedregulho, argila, saibro, basalto, etc.)", 'I-1', 40],
  ["Extração, beneficiamento, britamento, pelotização e sinterização de minérios ferrosos e não-ferrosos (ferro, alumínio, estanho, manganês, metais preciosos, minerais radioativos, nióbio, titânio, tungstênio, níquel, cobre, chumbo, zinco, etc.)", 'I-1', 200],
  ["Extração, refino e outros tratamentos de sal", 'I-1', 40],
  ["Farinha de mandioca e derivados (produtos, moagem, beneficiamento)", 'I-3', 2000],
  ["Farinha de milho e derivados, exceto óleos de milho (produtos, moagem, beneficiamento)", 'I-3', 2000],
  ["Farmoquímicos", 'I-1', 300],
  ["Fermentos e leveduras", 'I-2', 800],
  ["Ferramentas", 'I-1', 200],
  ["Ferro (fundição)", 'I-1', 40],
  ["Ferro (outros tubos)", 'I-1', 200],
  ["Ferro-gusa", 'I-1', 200],
  ["Ferroligas", 'I-1', 200],
  ["Fiação de fibras de algodão e fibras têxteis naturais", 'I-2', 700],
  ["Fibras artificiais e sintéticas", 'I-1', 300],
  ["Fios, cabos e condutores elétricos isolados", 'I-1', 300],
  ["Flores artificiais", 'I-1', 300],
  ["Formulação de combustíveis", 'I-3', 4000],
  ["Formulários contínuos", 'I-2', 500],
  ["Fornos industriais, aparelhos e equipamentos não- elétricos para instalações térmicas, peças e acessórios", 'I-1', 200],
  ["Fraldas descartáveis", 'I-2', 1000],
  ["Frigorífico", 'I-3', 2000],
  ["Frutas cristalizadas, balas e semelhantes", 'I-2', 400],
  ["Gases em geral (exceto inflamáveis)", 'I-2', 700],
  ["Gelo", 'I-1', 80],
  ["Geradores de corrente contínua e alternada, peças e acessórios", 'I-1', 300],
  ["Guarda-chuvas e similares", 'I-1', 300],
  ["Impermeabilizantes, solventes e produtos afins", 'I-3', 4000],
  ["Impressão em geral (livros, jornais, revistas e outros)", 'I-2', 400],
  ["Instrumentos musicais, peças e acessórios", 'I-2', 600],
  ["Instrumentos não- eletrônicos e utensílios para uso médico, cirúrgico, odontológico e de laboratório", 'I-1', 300],
  ["Intermediários para plastificantes, resinas e fibras", 'I-3', 3000],
  ["Jogos eletrônicos", 'I-1', 300],
  ["Lâmpadas, luminárias e outros equipamentos de iluminação", 'I-1', 40],
  ["Lapidação de gemas", 'I-1', 200],
  ["Leite e laticínios", 'I-1', 200],
  ["Linhas para costura e bordar", 'I-2', 600],
  ["Locomotivas, vagões e outros materiais rodantes", 'I-1', 200],
  ["Madeira (embalagens)", 'I-2', 800],
  ["Madeira laminada e de chapas de madeira compensada, prensada e aglomerada", 'I-2', 800],
  ["Máquinas de escrever, calcular e outros equipamentos não-eletrônicos para escritório, peças e acessórios", 'I-1', 300],
  ["Máquinas e equipamentos para a agricultura e pecuária, peças e acessórios, exceto para irrigação", 'I-1', 300],
  ["Máquinas e equipamentos para a indústria do plástico, peças e acessórios", 'I-1', 200],
  ["Máquinas e equipamentos para a indústria têxtil, peças e acessórios", 'I-1', 200],
  ["Máquinas e equipamentos para a prospecção e extração de petróleo, peças e acessórios", 'I-1', 200],
  ["Máquinas e equipamentos para as indústrias de alimentos, bebidas e fumo, peças e acessórios", 'I-1', 200],
  ["Máquinas e equipamentos para as indústrias de celulose, papel e papelão e artefatos, peças e acessórios", 'I-1', 200],
  ["Máquinas e equipamentos para as indústrias do vestuário, do couro e de calçados, peças e acessórios", 'I-1', 200],
  ["Máquinas e equipamentos para saneamento básico e ambiental, peças e acessórios", 'I-1', 200],
  ["Máquinas e equipamentos para terraplenagem, pavimentação e construção, peças e acessórios, exceto tratores", 'I-1', 300],
  ["Máquinas e equipamentos para uso geral não especificados nesta tabela, peças e acessórios", 'I-1', 200],
  ["Máquinas e equipamentos para uso industrial específico não especificados nesta tabela, peças e acessórios", 'I-1', 200],
  ["Máquinas para a indústria metalúrgica, peças e acessórios, exceto máquinas- ferramenta", 'I-1', 200],
  ["Máquinas, equipamentos e aparelhos para transporte e elevação de cargas, peças e acessórios", 'I-1', 200],
  ["Máquinas, equipamentos e aparelhos para transporte e elevação de pessoas, peças e acessórios", 'I-1', 200],
  ["Máquinas-ferramenta, peças e acessórios em geral", 'I-1', 200],
  ["Margarina e outras gorduras vegetais e de óleos não- comestíveis de animais", 'I-2', 1000],
  ["Massas alimentícias", 'I-2', 1000],
  ["Matadouro / Abate de Animais", 'I-1', 40],
  ["Materiais para medicina e odontologia", 'I-1', 300],
  ["Material elétrico e eletrônico para veículos automotores, exceto baterias", 'I-1', 300],
  ["Material elétrico para instalações em circuito de consumo", 'I-1', 200],
  ["Medicamentos alopáticos, homeopáticos e fitoterápicos", 'I-1', 300],
  ["Mesas de bilhar, de sinuca e acessórios", 'I-2', 600],
  ["Metais não-ferrosos e suas ligas (forja)", 'I-1', 200],
  ["Metais não-ferrosos e suas ligas (fundição)", 'I-1', 40],
  ["Metal (produtos em geral, trefilados, esquadrias, artefatos estampados, artigos para uso doméstico e pessoal)", 'I-1', 200],
  ["Metal e ligas metálicas (embalagens)", 'I-1', 200],
  ["Metalurgia de metais não-ferrosos e suas ligas não especificados nesta tabela", 'I-1', 200],
  ["Metalurgia em geral (do pó, do cobre, dos metais preciosos)", 'I-1', 200],
  ["Mídias virgens, magnéticas e ópticas", 'I-2', 600],
  ["Minerais não-metálicos não especificados nesta tabela", 'I-1', 40],
  ["Mobiliário para uso médico, cirúrgico, odontológico e de laboratório", 'I-2', 600],
  ["Motocicletas", 'I-1', 300],
  ["Motores e turbinas, peças e acessórios, exceto para aviões e veículos rodoviários", 'I-1', 200],
  ["Motores elétricos, peças e acessórios", 'I-1', 300],
  ["Motores para automóveis", 'I-1', 300],
  ["Móveis em geral", 'I-2', 600],
  ["Obras de caldeiraria pesada", 'I-1', 200],
  ["Óleos lubrificantes (exceto combustíveis ou inflamáveis)", 'I-3', 4000],
  ["Óleos vegetais (exceto combustíveis ou inflamáveis)", 'I-2', 1000],
  ["Padaria e Confeitaria com produção própria", 'I-2', 1000],
  ["Painéis e letreiros Luminosos", 'I-2', 600],
  ["Papel (embalagens)", 'I-2', 800],
  ["Papel e papelão em geral (exceto papelão betuminado)", 'I-2', 800],
  ["Papel e similares para uso comercial e de escritório", 'I-2', 800],
  ["Papelão betuminado", 'I-3', 2000],
  ["Peças e acessórios para veículos automotores", 'I-1', 300],
  ["Peças e acessórios para veículos ferroviários", 'I-1', 200],
  ["Periféricos para equipamentos de informática", 'I-1', 300],
  ["Petróleo (produtos do refino e derivados em geral)", 'I-3', 4000],
  ["Pilhas, baterias e acumuladores elétricos", 'I-2', 800],
  ["Placas e letreiros de qualquer material, exceto luminosos", 'I-2', 500],
  ["Plástico em geral (artefatos em geral, embalagens, aminados planos, tubulares, tubos e acessórios de uso na construção)", 'I-2', 1000],
  ["Plastificantes: produtos químicos orgânicos não especificados nesta tabela (não solventes)", 'I-3', 2000],
  ["Plastificantes: produtos químicos orgânicos não especificados nesta tabela (solventes)", 'I-3', 4000],
  ["Pneus, pneumáticos e câmaras de ar", 'I-2', 700],
  ["Pós alimentícios (alimentos ou preparados em pó)", 'I-2', 800],
  ["Preparações farmacêuticas", 'I-1', 300],
  ["Processamento de lixo com alta carga de incêndio", 'I-3', null, "Anexo B ou C"],
  ["Processamento de lixo com baixa carga de incêndio", 'I-1', null, "Anexo B ou C"],
  ["Processamento de lixo com média carga de incêndio", 'I-2', null, "Anexo B ou C"],
  ["Produção e distribuição de vapor, água quente e ar condicionado", 'I-1', 200],
  ["Produtos à base de café", 'I-2', 400],
  ["Produtos alimentícios não especificados nesta tabela", 'I-2', 1000],
  ["Produtos de carne", 'I-2', 500],
  ["Produtos de limpeza e polimento", 'I-3', 2000],
  ["Produtos de origem vegetal não especificados nesta tabela", 'I-3', 2000],
  ["Produtos de panificação industrial", 'I-2', 1000],
  ["Produtos derivados do cacau e de chocolates", 'I-2', 400],
  ["Produtos para infusão (chá, mate e similares)", 'I-2', 1000],
  ["Produtos petroquímicos básicos", 'I-3', 4000],
  ["Produtos químicos inorgânicos não especificados nesta tabela", 'I-2', 500],
  ["Produtos químicos orgânicos não especificados nesta tabela", 'I-2', 1000],
  ["Recondicionamento e recuperação de motores para veículos Automotores (exceto oficina de conserto de veículos)", 'I-1', 300],
  ["Refrescos, xaropes e pós solúveis para refrescos", 'I-1', 80],
  ["Resinas termofixas e resinas termoplásticas", 'I-3', 3000],
  ["Rolamentos para fins industriais", 'I-1', 200],
  ["Roupas em geral, peças de vestuário e acessórios", 'I-2', 500],
  ["Sabões e detergentes sintéticos", 'I-1', 300],
  ["Sanitário de cerâmica", 'I-1', 200],
  ["Serrarias", 'I-2', 800],
  ["Serviços de confecção de armações metálicas para a construção", 'I-1', 200],
  ["Serviços de pré-impressão", 'I-2', 400],
  ["Serviços de prótese dentária", 'I-1', 200],
  ["Serviços de tratamento e revestimento em metais", 'I-1', 200],
  ["Serviços de usinagem, tornearia e solda", 'I-1', 200],
  ["Soldas e ânodos para galvanoplastia", 'I-1', 200],
  ["Som em qualquer suporte", 'I-2', 600],
  ["Sorvetes e outros gelados comestíveis", 'I-1', 80],
  ["Tanques, reservatórios metálicos e caldeiras para aquecimento central", 'I-1', 200],
  ["Tecelagem de fios de fibras têxteis naturais", 'I-2', 600],
  ["Tecidos especiais, inclusive artefatos", 'I-2', 700],
  ["Têxteis e tecidos em geral", 'I-2', 700],
  ["Tintas de impressão", 'I-3', 4000],
  ["Tintas, vernizes, esmaltes e lacas", 'I-3', 4000],
  ["Torrefação e moagem de café", 'I-2', 400],
  ["Transformadores, indutores, conversores, sincronizadores e semelhantes, peças e acessórios", 'I-1', 200],
  ["Tratores, peças e acessórios", 'I-1', 300],
  ["Trigo (produtos, moagem, beneficiamento)", 'I-3', 2000],
  ["Turbinas, motores e outros componentes e peças para aeronaves", 'I-2', 600],
  ["Válvulas, registros e dispositivos semelhantes, peças e acessórios", 'I-1', 200],
  ["Veículos militares de combate", 'I-1', 300],
  ["Velas (inclusive decorativa)", 'I-3', 2000],
  ["Vidro (embalagens)", 'I-2', 700],
  ["Vidro (outros não especificado nesta tabela)", 'I-2', 700],
  ["Vidro plano e de segurança", 'I-1', 200],
  ["Vinagres", 'I-1', 80],
  ["Zinco (laminados e em formas primárias)", 'I-1', 200],
  ["Depósitos e similares de material incombustível (sem embalagem ou com embalagem incombustível)", 'J-1', null, "Anexo B ou C"],
  ["Depósitos e similares com carga de incêndio baixa", 'J-2', null, "Anexo B ou C"],
  ["Depósitos e similares com carga de incêndio média", 'J-3', null, "Anexo B ou C"],
  ["Depósitos e similares com carga de incêndio alta", 'J-4', null, "Anexo B ou C"],
  ["Comércio varejista de fogos de artifício e artigos pirotécnicos", 'L-1', 4000],
  ["Depósito de pólvora, explosivos, detonantes e similares", 'L-3', null, "Anexo C"],
  ["Fabricação de armas de fogo, outras armas e munições", 'L-2', 4000],
  ["Fabricação de artigos pirotécnicos", 'L-2', 4000],
  ["Fabricação de equipamento bélico pesado, exceto veículos militares de combate", 'L-2', 4000],
  ["Fabricação de fertilizantes cujos componentes possuem característica potencialmente explosiva ou combustível", 'L-2', 4000],
  ["Fabricação de fósforos de segurança", 'L-2', 4000],
  ["Fabricação de pólvoras, explosivos e detonantes", 'L-2', 4000],
  ["Agronegócio (edificações e instalações destinadas à plantação ou criação de animais)", 'M-8', null, "Anexo C"],
  ["Armazenamento e processos de grãos e assemelhados", 'M-5', null, "Anexo C"],
  ["Canteiro de obras e assemelhados (instalações de apoio)", 'M-4', null, "Conforme atividade (ocupação) específica"],
  ["Centrais de processamento de dados", 'M-3', 400],
  ["Centrais de transmissão e de distribuição de energia", 'M-3', 200],
  ["Centrais telefônicas", 'M-3', 100],
  ["Centros de comunicação", 'M-3', 100],
  ["Comércio atacadista de biodiesel, gasolina e demais derivados de petróleo", 'M-2', 4000],
  ["Comércio atacadista de combustíveis de origem vegetal e mineral em bruto", 'M-2', 4000],
  ["Comércio atacadista de lubrificantes", 'M-2', 4000],
  ["Comércio de gás liquefeito de petróleo (GLP)", 'M-2', 4000],
  ["Distribuição de combustíveis gasosos por redes urbanas", 'M-2', 4000],
  ["Florestas, reservas ecológicas, parques florestais e assemelhados", 'M-6', 3000],
  ["Geração de energia elétrica", 'M-3', 600],
  ["Geração de energia - outras (eólica, solar, fotovoltaica, termoelétrica)", 'M-3', null, "Anexo C"],
  ["Pátio de containers", 'M-7', null, "Anexo C"],
  ["Produção de gás; processamento de gás natural", 'M-2', 4000],
  ["Silos", 'M-5', null, "Anexo C"],
  ["Túnel", 'M-1', null, "Anexo C"],
];
